### PR TITLE
[IMP] add tracking=True parameter for exc_info var

### PR DESCRIPTION
**Pull request by KirylSudnikovich**
Add tracking=True parameter for exc_info field as a part of https://github.com/novacode-nl/odoo-celery/issues/16 issue.

### CODE REVIEW

**Review by ovnicraft — APPROVED** [review]

**Comment by bobslee** [comment]
@ovnicraft you reviewed and tested this?

**Comment by ovnicraft** [comment]
Reviewed it, not tested yet, I am starting working with this module.

**Comment by bobslee** [comment]
Ok. I'am not sure how this change affects heavy task queues, with lots of tasks.
So I rather would like to test this, however I've no time to spend this effort.

I suggest I merge this and see how it goes. Right?
cc @0311snitch

**Comment by ovnicraft** [comment]
Yep, let's see :)

**Pull request merged**
