### PR TITLE
Initial upgrade to 17.0

### PR DESCRIPTION
**Pull request by Maralai**
I am working on implementing this celery repo in Odoo 17.0. I found the following issues that either prevented the application from installing or provided a less-than-desirable UI experience. 

This may not be comprehensive as:
-  I have not fully implemented the repo.
-  I have not ran the celery_example module.

### CODE REVIEW

**Comment by Maralai** [comment]
This belongs on a new branch.

**Comment by bobslee** [comment]
@Maralai I just reviewed your PR. Looks good!

However, I don't have time to test this and I don't use the Celery module anymore.
The OCA queue_job is just better maintained.
Out of curiosity, why do you use this celery module instead of OCA queue_job?

If you can migrate and test with the `celery_example` module, please do.
I'm willingly to merge the PR then.

**Comment by Maralai** [comment]
I recalled celery from a few years back, and I didn't remember queue_job. I have just implemented queue_job instead, however. 

I do have a few projects with celery broker, though not odoo, so I might revisit this someday. But probably won't be for a while.

Thanks!

**Comment by scwall** [comment]
Hi there,
I did the same and adapted the code for odoo 17 I also sent my pull requests, I had not seen that you had done the same thing I tested with the celery example module and everything seems to work, however I'm not sure of a feature or I looked for an alternative but did not find it :
https://github.com/novacode-nl/odoo-celery/pull/46

**Comment by bobslee** [comment]
@Maralai , @scwall please can you review and let me know which PR I should merge?
I'm sorry but I don't have any free time for a while, to review/analyse this.

When I get your proposal I will review the final PR and merge.
Thanks!

**Comment by scwall** [comment]
Hello,
Since I haven't seen an answer from @Maralai , can you create the branch? In my case, everything works, but I'd like to have your opinion on the code concerning the model and the self._cr.after('commit', apply_call_task) part. This no longer exists in the new versions of odoo, so I've done things differently.

**Pull request closed without merging**
